name: Skins
version: '${project.version}'
main: me.nes0x.skins.Skins
api-version: 1.16
authors: [ Nes0x ]
description: Skins from your resource pack

commands:
  skin:
    usage: /skin <category> <name>
  giveskin:
    usage: /giveskin <player> <category> <name>
  skins:
    usage: /skins
    aliases: 
      - skiny

permissions:
  skins.commands.skin:
    default: op
    description: Permission to command /skin <category> <name>
  skins.commands.giveskin:
    default: op
    description: Permission to command /giveskin <player> <category> <name>
  skins.commands.skins:
    default: true
    description: Permission to command /skins
  skins.commands.*:
    default: op
    description: Permission to all commands
    children:
      skins.commands.skin: true
      skins.commands.giveskin: true
      skins.commands.skins: true
